blank_issues_enabled: false
contact_links:
  - name: Lime Discord
    url: https://discord.com/invite/4ZjMpAp3M6
    about: If you are experiencing an issue with Lime, and you need tech support, or if you have a general question, try asking in the official Lime Discord linked here. Piracy is not allowed.
